let greeting = "Hello";
let price=10.11;
let quantity=4;
const total= price*quantity;
const age1 = 53;
const age2 = 34;
const age3 = 34;
const averageAge = (age1 + age2 + age3)/3;
const loggedIn =true;
const adminUser = false;
let missingInfo;